language: node_js
node_js:
    - "0.10"
    - "0.12"
    - "4.0"
before_install:
    - cd db
    - sqlite3 CC_calificacionEmpresa.db
    - .read creacionTablasBD.sql
    - .quit
    - cd ..
#script: 
#    - cd src; npm test